

/** Object to find the party logo */
module.exports = {
    'FE-UF': 'images/ico/fe-uf-ico.jpg',
    'UF-FI-AT': 'images/ico/no-ico.png',
    'CIME': 'images/ico/no-ico.png',
    'POC': 'images/ico/no-ico.png',
    'PIPPA': 'images/ico/no-ico.png',
    'FEA': 'images/ico/no-ico.png',
    'CNA': 'images/ico/no-ico.png',
    'LC': 'images/ico/no-ico.png',
    'ARDE': 'images/ico/no-ico.png',
    'PPROV': 'images/ico/no-ico.png',
    'DSCC': 'images/ico/no-ico.png',
    'CIC': 'images/ico/no-ico.png',
    'P-CANT': 'images/ico/no-ico.png',
    'E CATALA': 'images/ico/no-ico.png',
    'ULE': 'images/ico/no-ico.png',
    'PSIN': 'images/ico/no-ico.png',
    'SMIM': 'images/ico/no-ico.png',
    'PDPCAN': 'images/ico/no-ico.png',
    'PRE': 'images/ico/no-ico.png',
    'UNAI': 'images/ico/no-ico.png',
    'PNPV': 'images/ico/no-ico.png',
    'URV': 'images/ico/no-ico.png',
    'PLIB': 'images/ico/no-ico.png',
    'PANCAL': 'images/ico/no-ico.png',
    'PSAR - PSDA': 'images/ico/no-ico.png',
    'UPN': 'images/ico/no-ico.png',
    'FJONSA': 'images/ico/no-ico.png',
    'UFV': 'images/ico/no-ico.png',
    'LCR': 'images/ico/no-ico.png',
    'PAR': 'images/ico/no-ico.png',
    'PCT': 'images/ico/no-ico.png',
    'OCEBR-UCE': 'images/ico/no-ico.png',
    'PCARL': 'images/ico/no-ico.png',
    'IR': 'images/ico/no-ico.png',
    'PG-POG-PSG': 'images/ico/no-ico.png',
    'BEAN': 'images/ico/no-ico.png',
    'C-UPC': 'images/ico/no-ico.png',
    'BNPG': 'images/ico/no-ico.png',
    'MC-OIC': 'images/ico/no-ico.png',
    'EE': 'images/ico/no-ico.png',
    'ERFN': 'images/ico/no-ico.png',
    'ORT': 'images/ico/no-ico.png',
    'BNG': 'images/ico/no-ico.png',
    'EA': 'images/ico/no-ico.png',
    'PSOE-H': 'images/ico/no-ico.png',
    'HB': 'images/ico/no-ico.png',
    'PTE': 'images/ico/no-ico.png',
    'PNV': 'images/ico/eaj-pnv-ico.jpg',
    'EAJ-PNV': 'images/ico/eaj-pnv-ico.jpg',
    'PSA-PA': 'images/ico/psa-pa-ico.png',
    'UN': 'images/ico/no-ico.png',
    'CIU': 'images/ico/ciu-ico.png',
    'CD': 'images/ico/cd-ico.jpg',
    'CDS': 'images/ico/cds-ico.png',
    'PCE': 'images/ico/pce-ico.png',
    'PSOE': 'images/ico/psoe-ico.jpg',
    'UCD': 'images/ico/ucd-ico.jpg',
    'PP': 'images/ico/pp-ico.jpg',
    'ERC': 'images/ico/erc-ico.png',
    'IU': 'images/ico/iu-ico.jpg',
    'CC': 'images/ico/cc-ico.png',
    'PODEMOS': 'images/ico/podemos-ico.png',
    'CIUDADANOS': 'images/ico/ciudadanos-ico.jpg'
};