/* jshint esversion: 6 */

/**
 * Object to find the party color
 * @module modules/graphics/colors
 */
module.exports = {
    'FE-UF': 'blue',
    'UF-FI-AT': 'blue',
    'CIME': 'blue',
    'POC': 'blue',
    'PIPPA': 'blue',
    'FEA': 'blue',
    'CNA': 'blue',
    'LC': 'blue',
    'ARDE': 'blue',
    'PPROV': 'blue',
    'DSCC': 'blue',
    'CIC': 'blue',
    'P-CANT': 'blue',
    'E CATALA': 'blue',
    'ULE': 'blue',
    'PSIN': 'blue',
    'SMIM': 'blue',
    'PDPCAN': 'blue',
    'PRE': 'blue',
    'UNAI': 'blue',
    'PNPV': 'blue',
    'URV': 'blue',
    'PLIB': 'blue',
    'PANCAL': 'blue',
    'PSAR - PSDA': 'blue',
    'UPN': 'blue',
    'FJONSA': 'blue',
    'UFV': 'blue',
    'LCR': 'blue',
    'PAR': 'blue',
    'PCT': 'blue',
    'OCEBR-UCE': 'blue',
    'PCARL': 'blue',
    'IR': 'blue',
    'PG-POG-PSG': 'blue',
    'BEAN': 'blue',
    'C-UPC': 'blue',
    'BNPG': 'blue',
    'MC-OIC': 'blue',
    'EE': 'blue',
    'ERFN': 'blue',
    'ORT': 'blue',
    'PSOE-H': 'blue',
    'HB': 'blue',
    'PTE': 'blue',
    'PNV': '#008140',
    'PSA-PA': 'blue',
    'UN': 'blue',
    'CIU': 'blue',
    'CD': 'blue',
    'PCE': 'blue',
    'PSOE': '#E3001B',
    'UCD': '#177D34',
    'PP': '#0067C3',
    'PODEMOS': '#6B1F5F',
    'CIUDADANOS': '#F58424'
};