'use strict';
/**
 * Object to find the party color
 * @module modules/functions/colors
 */
module.exports = {
        'FE-UF': 'blue',
        'UF-FI-AT': 'blue',
        'CIME': 'blue',
        'POC': 'blue',
        'PIPPA': 'blue',
        'FEA': 'blue',
        'CNA': 'blue',
        'LC': 'blue',
        'ARDE': 'blue',
        'PPROV': 'blue',
        'DSCC': 'blue',
        'CIC': 'blue',
        'P-CANT': 'blue',
        'E CATALA': 'blue',
        'ULE': 'blue',
        'PSIN': 'blue',
        'SMIM': 'blue',
        'PDPCAN': 'blue',
        'PRE': 'blue',
        'UNAI': 'blue',
        'PNPV': 'blue',
        'URV': 'blue',
        'PLIB': 'blue',
        'PANCAL': 'blue',
        'PSAR - PSDA': 'blue',
        'UPN': 'blue',
        'FJONSA': 'blue',
        'UFV': 'blue',
        'LCR': 'blue',
        'PAR': 'blue',
        'PCT': 'blue',
        'OCEBR-UCE': 'blue',
        'PCARL': 'blue',
        'IR': 'blue',
        'PG-POG-PSG': 'blue',
        'BEAN': 'blue',
        'C-UPC': 'blue',
        'BNPG': 'blue',
        'MC-OIC': 'blue',
        'EE': 'blue',
        'ERFN': 'blue',
        'ORT': 'blue',
        'PSOE-H': 'blue',
        'HB': 'blue',
        'PTE': 'blue',
        'PNV': 'blue',
        'PSA-PA': 'blue',
        'UN': 'blue',
        'CIU': 'blue',
        'CD': 'blue',
        'PCE': 'blue',
        'PSOE': 'red',
        'UCD': 'blue',
        'PP': 'blue',
        'PODEMOS': 'blue',
        'CIUDADANOS': 'blue'
};