/* jshint esversion: 6 */

/**
 * Object to find the party logo
 * @module modules/graphics/icons
 */
module.exports = {
    'FE-UF': 'images/no-ico.png',
    'UF-FI-AT': 'images/no-ico.png',
    'CIME': 'images/no-ico.png',
    'POC': 'images/no-ico.png',
    'PIPPA': 'images/no-ico.png',
    'FEA': 'images/no-ico.png',
    'CNA': 'images/no-ico.png',
    'LC': 'images/no-ico.png',
    'ARDE': 'images/no-ico.png',
    'PPROV': 'images/no-ico.png',
    'DSCC': 'images/no-ico.png',
    'CIC': 'images/no-ico.png',
    'P-CANT': 'images/no-ico.png',
    'E CATALA': 'images/no-ico.png',
    'ULE': 'images/no-ico.png',
    'PSIN': 'images/no-ico.png',
    'SMIM': 'images/no-ico.png',
    'PDPCAN': 'images/no-ico.png',
    'PRE': 'images/no-ico.png',
    'UNAI': 'images/no-ico.png',
    'PNPV': 'images/no-ico.png',
    'URV': 'images/no-ico.png',
    'PLIB': 'images/no-ico.png',
    'PANCAL': 'images/no-ico.png',
    'PSAR - PSDA': 'images/no-ico.png',
    'UPN': 'images/no-ico.png',
    'FJONSA': 'images/no-ico.png',
    'UFV': 'images/no-ico.png',
    'LCR': 'images/no-ico.png',
    'PAR': 'images/no-ico.png',
    'PCT': 'images/no-ico.png',
    'OCEBR-UCE': 'images/no-ico.png',
    'PCARL': 'images/no-ico.png',
    'IR': 'images/no-ico.png',
    'PG-POG-PSG': 'images/no-ico.png',
    'BEAN': 'images/no-ico.png',
    'C-UPC': 'images/no-ico.png',
    'BNPG': 'images/no-ico.png',
    'MC-OIC': 'images/no-ico.png',
    'EE': 'images/no-ico.png',
    'ERFN': 'images/no-ico.png',
    'ORT': 'images/no-ico.png',
    'PSOE-H': 'images/no-ico.png',
    'HB': 'images/no-ico.png',
    'PTE': 'images/no-ico.png',
    'PNV': 'images/no-ico.png',
    'PSA-PA': 'images/no-ico.png',
    'UN': 'images/no-ico.png',
    'CIU': 'images/no-ico.png',
    'CD': 'images/no-ico.png',
    'PCE': 'images/pce-ico.png',
    'PSOE': 'images/psoe-ico.jpg',
    'UCD': 'images/ucd-ico.jpg',
    'PP': 'images/no-ico.png',
    'PODEMOS': 'images/no-ico.png',
    'CIUDADANOS': 'images/no-ico.png'
};