/**
 * Rutas de la interfaz web
 */

'use strict';
const express = require('express'),
    router = express.Router(),
    IndexFunctions = require('./../modules/functions/index-functions');

/**
 * Welcome route.
 */
router.get('/', IndexFunctions.indexGetFunction);

/**
 * Help route.
 */
router.get('/help', IndexFunctions.helpGetFunction);

/**
 * Leaflet Example Route
 */
router.get('/leaflet-example', IndexFunctions.leafletExampleGetFunction);

/**
 * GET Form to create graphs with stored results
 */
router.get('/graphic-form', IndexFunctions.graphicFormGetFunction);

/**
 * GET Learn
 */
router.get('/learn', IndexFunctions.learnGetFunction);

/**
 * GET Add data
 */
router.get('/add-data', IndexFunctions.addDataGetFunction);

/**
 * POST Add data
 */
router.post('/add-data', IndexFunctions.addDataPostFunction);

/**
 * GET Delete data
 */
router.get('/delete-data', IndexFunctions.deleteDataGetFunction);

/**
 * POST Delete data
 */
router.post('/delete-data', IndexFunctions.deleteDataPostFunction);

/**
 * POST show the graph generated by the form
 */
router.post('/graphic-form', IndexFunctions.graphicFormPostFunction);

module.exports = router;
